import os
import yaml
import pandas as pd
import json

from src.models.train_baselines import load_data, get_models, PREDICTIVE_FEATURES
from src.models.evaluate_baselines import get_metrics
from src.models.mlflow_tracking import (
    initialize_mlflow, start_run, log_parameters, log_metrics,
    log_artifact_file, log_model, add_tags
)

def run_mlflow_baselines():
    # Load configs
    with open('configs/mlflow_config.yaml', 'r') as f:
        mlflow_config = yaml.safe_load(f)['mlflow']
        
    with open('configs/model_config.yaml', 'r') as f:
        model_config = yaml.safe_load(f)['models']
        
    with open('configs/split_config.yaml', 'r') as f:
        split_config = yaml.safe_load(f)['split']
        
    initialize_mlflow(mlflow_config['tracking_uri'], mlflow_config['experiment_name'])
    
    # Load data
    train = pd.read_parquet('data/processed/splits/train.parquet')
    val = pd.read_parquet('data/processed/splits/validation.parquet')
    test = pd.read_parquet('data/processed/splits/test.parquet')
    
    splits = {'train': train, 'validation': val, 'test': test}
    for name, df in splits.items():
        num_cols = [f for f in PREDICTIVE_FEATURES if f not in ['highest_education', 'code_module', 'code_presentation']]
        for c in num_cols:
            df[c] = pd.to_numeric(df[c], errors='coerce')
            
    X_train = train[PREDICTIVE_FEATURES]
    y_train = train['is_withdrawn']
    
    models = get_models(model_config)
    
    # Create comparison artifacts directory
    os.makedirs('reports/models', exist_ok=True)
    comparison_data = []
    
    for model_key, model_pipeline in models.items():
        run_name = f"baseline_{'logistic_regression' if model_key == 'lr' else 'random_forest' if model_key == 'rf' else 'xgboost'}"
        
        with start_run(run_name=run_name) as run:
            run_id = run.info.run_id
            print(f"Running {run_name} (Run ID: {run_id})...")
            
            # Tags
            add_tags({
                'project': 'equitable_student_dropout',
                'task': 'student_withdrawal_prediction',
                'cutoff': 'day28',
                'fairness_aware': 'planned',
                'baseline': 'true',
                'data_version': 'dvc_managed',
                'split_strategy': 'stratified_group_kfold',
                'random_state': str(model_config['random_state'])
            })
            
            # Parameters
            params = {
                'dataset_name': 'oulad_day28',
                'cutoff_day': 28,
                'train_rows': len(train),
                'validation_rows': len(val),
                'test_rows': len(test),
                'positive_class': 1,
                'split_random_state': split_config['random_state'],
                'grouping_variable': split_config['group_col'],
                'predictive_feature_count': len(PREDICTIVE_FEATURES),
                'categorical_feature_count': 3,
                'numeric_feature_count': 18,
                'preprocessing_version': '1.0'
            }
            
            # Model specific parameters
            if model_key == 'lr':
                params['max_iter'] = model_config['logistic_regression']['max_iter']
            elif model_key == 'rf':
                params['n_estimators'] = model_config['random_forest']['n_estimators']
                params['n_jobs'] = model_config['random_forest']['n_jobs']
            elif model_key == 'xgb':
                params.update(model_config['xgboost'])
            
            log_parameters(params)
            
            # Train
            model_pipeline.fit(X_train, y_train)
            
            # Evaluate & log metrics
            test_metrics_for_csv = {'run_id': run_id, 'model': model_key}
            
            for split_name, df in splits.items():
                X = df[PREDICTIVE_FEATURES]
                y = df['is_withdrawn']
                
                m = get_metrics(model_pipeline, X, y)
                metrics_to_log = {}
                for k, v in m.items():
                    if k not in ['cm', 'probs']:
                        metrics_to_log[f"{split_name}_{k}"] = v
                        if split_name == 'test':
                            test_metrics_for_csv[f"test_{k}"] = v
                            
                log_metrics(metrics_to_log)
                
            comparison_data.append(test_metrics_for_csv)
            
            # Artifacts (Confusion matrix and ROC/PR already generated by evaluate_baselines.py)
            # We assume they exist or we log the ones that exist. But the prompt says "Log the existing confusion-matrix plots".
            cm_path = f"reports/models/{model_key}_cm.png"
            roc_path = f"reports/models/{model_key}_roc.png"
            pr_path = f"reports/models/{model_key}_pr.png"
            fi_path = f"reports/models/{model_key}_feature_importance.csv"
            
            for p in [cm_path, roc_path, pr_path, fi_path]:
                if os.path.exists(p):
                    log_artifact_file(p, artifact_path="plots" if "png" in p else "feature_importance")
            
            # Log Model
            reg_model_name = mlflow_config['registered_model_names'].get(model_key)
            log_model(
                model=model_pipeline, 
                artifact_path="model", 
                X_example=X_train.head(5),
                registered_model_name=reg_model_name
            )

    # Save summary
    pd.DataFrame(comparison_data).to_csv('reports/models/mlflow_baseline_runs.csv', index=False)
    print("MLflow tracking complete.")

if __name__ == "__main__":
    run_mlflow_baselines()
